name: Install
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cehckout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: npm install