name: Install
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cehckout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install